version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@grpc/proto-loader"
    versions:
    - 0.5.6
    - 0.6.0
  - dependency-name: "@grpc/grpc-js"
    versions:
    - 1.2.11
    - 1.2.7
  - dependency-name: google-protobuf
    versions:
    - 3.14.0
    - 3.15.1
    - 3.15.3
    - 3.15.6
  - dependency-name: jsdoc-to-markdown
    versions:
    - 7.0.0
  - dependency-name: "@malijs/call-types"
    versions:
    - 0.4.0
  - dependency-name: is-ci
    versions:
    - 3.0.0
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: ava
    versions:
    - 3.15.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: standard
    versions:
    - 16.0.3
  - dependency-name: snazzy
    versions:
    - 9.0.0
