name: Node CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, and test
      run: |
        npm ci
        npm test
      env:
        CI: true
    - name: Generate coverage
      if: success()
      run: |
        mkdir coverage
        npm run coverage
      env:
        CI: true
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel: true
    - name: Coveralls Finished
      if: success()
      uses: coverallsapp/github-action@master
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
